-- Seed hotel_media for all 40 hotels (5 deterministic placeholder images each = 200 rows).
-- Keyed by hotel name so it runs AFTER the hotels are inserted, regardless of their UUIDs.
-- Re-runnable guard: skips hotels that already have media.
-- TO GO LIVE: replace the picsum.photos URLs with your own CDN/licensed URLs (same rows).
INSERT INTO hotel_media (hotel_id, media_type, media_type_categories, media_url)
SELECT h.id, v.media_type::media_type, v.cat::media_type_categories, v.url
FROM hotels h
JOIN (VALUES
  ('Kigali Serena Hotel', 'photo', 'profile', 'https://picsum.photos/seed/kigali-serena-hotel-0/800/800'),
  ('Kigali Serena Hotel', 'photo', 'landscape', 'https://picsum.photos/seed/kigali-serena-hotel-1/1200/800'),
  ('Kigali Serena Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/kigali-serena-hotel-2/1200/800'),
  ('Kigali Serena Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/kigali-serena-hotel-3/1200/800'),
  ('Kigali Serena Hotel', 'photo', 'room', 'https://picsum.photos/seed/kigali-serena-hotel-4/1000/700'),
  ('Hôtel des Mille Collines', 'photo', 'profile', 'https://picsum.photos/seed/hotel-des-mille-collines-0/800/800'),
  ('Hôtel des Mille Collines', 'photo', 'landscape', 'https://picsum.photos/seed/hotel-des-mille-collines-1/1200/800'),
  ('Hôtel des Mille Collines', 'photo', 'gallery', 'https://picsum.photos/seed/hotel-des-mille-collines-2/1200/800'),
  ('Hôtel des Mille Collines', 'photo', 'gallery', 'https://picsum.photos/seed/hotel-des-mille-collines-3/1200/800'),
  ('Hôtel des Mille Collines', 'photo', 'room', 'https://picsum.photos/seed/hotel-des-mille-collines-4/1000/700'),
  ('Hotel Chez Lando', 'photo', 'profile', 'https://picsum.photos/seed/hotel-chez-lando-0/800/800'),
  ('Hotel Chez Lando', 'photo', 'landscape', 'https://picsum.photos/seed/hotel-chez-lando-1/1200/800'),
  ('Hotel Chez Lando', 'photo', 'gallery', 'https://picsum.photos/seed/hotel-chez-lando-2/1200/800'),
  ('Hotel Chez Lando', 'photo', 'gallery', 'https://picsum.photos/seed/hotel-chez-lando-3/1200/800'),
  ('Hotel Chez Lando', 'photo', 'room', 'https://picsum.photos/seed/hotel-chez-lando-4/1000/700'),
  ('Wilderness Sabyinyo Silverback Lodge', 'photo', 'profile', 'https://picsum.photos/seed/wilderness-sabyinyo-silverback-lodge-0/800/800'),
  ('Wilderness Sabyinyo Silverback Lodge', 'photo', 'landscape', 'https://picsum.photos/seed/wilderness-sabyinyo-silverback-lodge-1/1200/800'),
  ('Wilderness Sabyinyo Silverback Lodge', 'photo', 'gallery', 'https://picsum.photos/seed/wilderness-sabyinyo-silverback-lodge-2/1200/800'),
  ('Wilderness Sabyinyo Silverback Lodge', 'photo', 'gallery', 'https://picsum.photos/seed/wilderness-sabyinyo-silverback-lodge-3/1200/800'),
  ('Wilderness Sabyinyo Silverback Lodge', 'photo', 'room', 'https://picsum.photos/seed/wilderness-sabyinyo-silverback-lodge-4/1000/700'),
  ('Virunga Lodge', 'photo', 'profile', 'https://picsum.photos/seed/virunga-lodge-0/800/800'),
  ('Virunga Lodge', 'photo', 'landscape', 'https://picsum.photos/seed/virunga-lodge-1/1200/800'),
  ('Virunga Lodge', 'photo', 'gallery', 'https://picsum.photos/seed/virunga-lodge-2/1200/800'),
  ('Virunga Lodge', 'photo', 'gallery', 'https://picsum.photos/seed/virunga-lodge-3/1200/800'),
  ('Virunga Lodge', 'photo', 'room', 'https://picsum.photos/seed/virunga-lodge-4/1000/700'),
  ('Mountain Gorilla View Lodge', 'photo', 'profile', 'https://picsum.photos/seed/mountain-gorilla-view-lodge-0/800/800'),
  ('Mountain Gorilla View Lodge', 'photo', 'landscape', 'https://picsum.photos/seed/mountain-gorilla-view-lodge-1/1200/800'),
  ('Mountain Gorilla View Lodge', 'photo', 'gallery', 'https://picsum.photos/seed/mountain-gorilla-view-lodge-2/1200/800'),
  ('Mountain Gorilla View Lodge', 'photo', 'gallery', 'https://picsum.photos/seed/mountain-gorilla-view-lodge-3/1200/800'),
  ('Mountain Gorilla View Lodge', 'photo', 'room', 'https://picsum.photos/seed/mountain-gorilla-view-lodge-4/1000/700'),
  ('Hotel Muhabura', 'photo', 'profile', 'https://picsum.photos/seed/hotel-muhabura-0/800/800'),
  ('Hotel Muhabura', 'photo', 'landscape', 'https://picsum.photos/seed/hotel-muhabura-1/1200/800'),
  ('Hotel Muhabura', 'photo', 'gallery', 'https://picsum.photos/seed/hotel-muhabura-2/1200/800'),
  ('Hotel Muhabura', 'photo', 'gallery', 'https://picsum.photos/seed/hotel-muhabura-3/1200/800'),
  ('Hotel Muhabura', 'photo', 'room', 'https://picsum.photos/seed/hotel-muhabura-4/1000/700'),
  ('La Palme Hotel', 'photo', 'profile', 'https://picsum.photos/seed/la-palme-hotel-0/800/800'),
  ('La Palme Hotel', 'photo', 'landscape', 'https://picsum.photos/seed/la-palme-hotel-1/1200/800'),
  ('La Palme Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/la-palme-hotel-2/1200/800'),
  ('La Palme Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/la-palme-hotel-3/1200/800'),
  ('La Palme Hotel', 'photo', 'room', 'https://picsum.photos/seed/la-palme-hotel-4/1000/700'),
  ('Virunga Hotel', 'photo', 'profile', 'https://picsum.photos/seed/virunga-hotel-0/800/800'),
  ('Virunga Hotel', 'photo', 'landscape', 'https://picsum.photos/seed/virunga-hotel-1/1200/800'),
  ('Virunga Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/virunga-hotel-2/1200/800'),
  ('Virunga Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/virunga-hotel-3/1200/800'),
  ('Virunga Hotel', 'photo', 'room', 'https://picsum.photos/seed/virunga-hotel-4/1000/700'),
  ('Kinigi Guesthouse', 'photo', 'profile', 'https://picsum.photos/seed/kinigi-guesthouse-0/800/800'),
  ('Kinigi Guesthouse', 'photo', 'landscape', 'https://picsum.photos/seed/kinigi-guesthouse-1/1200/800'),
  ('Kinigi Guesthouse', 'photo', 'gallery', 'https://picsum.photos/seed/kinigi-guesthouse-2/1200/800'),
  ('Kinigi Guesthouse', 'photo', 'gallery', 'https://picsum.photos/seed/kinigi-guesthouse-3/1200/800'),
  ('Kinigi Guesthouse', 'photo', 'room', 'https://picsum.photos/seed/kinigi-guesthouse-4/1000/700'),
  ('Lake Kivu Serena Hotel', 'photo', 'profile', 'https://picsum.photos/seed/lake-kivu-serena-hotel-0/800/800'),
  ('Lake Kivu Serena Hotel', 'photo', 'landscape', 'https://picsum.photos/seed/lake-kivu-serena-hotel-1/1200/800'),
  ('Lake Kivu Serena Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/lake-kivu-serena-hotel-2/1200/800'),
  ('Lake Kivu Serena Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/lake-kivu-serena-hotel-3/1200/800'),
  ('Lake Kivu Serena Hotel', 'photo', 'room', 'https://picsum.photos/seed/lake-kivu-serena-hotel-4/1000/700'),
  ('Moriah Hill Resort', 'photo', 'profile', 'https://picsum.photos/seed/moriah-hill-resort-0/800/800'),
  ('Moriah Hill Resort', 'photo', 'landscape', 'https://picsum.photos/seed/moriah-hill-resort-1/1200/800'),
  ('Moriah Hill Resort', 'photo', 'gallery', 'https://picsum.photos/seed/moriah-hill-resort-2/1200/800'),
  ('Moriah Hill Resort', 'photo', 'gallery', 'https://picsum.photos/seed/moriah-hill-resort-3/1200/800'),
  ('Moriah Hill Resort', 'photo', 'room', 'https://picsum.photos/seed/moriah-hill-resort-4/1000/700'),
  ('Home Saint Jean', 'photo', 'profile', 'https://picsum.photos/seed/home-saint-jean-0/800/800'),
  ('Home Saint Jean', 'photo', 'landscape', 'https://picsum.photos/seed/home-saint-jean-1/1200/800'),
  ('Home Saint Jean', 'photo', 'gallery', 'https://picsum.photos/seed/home-saint-jean-2/1200/800'),
  ('Home Saint Jean', 'photo', 'gallery', 'https://picsum.photos/seed/home-saint-jean-3/1200/800'),
  ('Home Saint Jean', 'photo', 'room', 'https://picsum.photos/seed/home-saint-jean-4/1000/700'),
  ('Hotel Centre Bethanie', 'photo', 'profile', 'https://picsum.photos/seed/hotel-centre-bethanie-0/800/800'),
  ('Hotel Centre Bethanie', 'photo', 'landscape', 'https://picsum.photos/seed/hotel-centre-bethanie-1/1200/800'),
  ('Hotel Centre Bethanie', 'photo', 'gallery', 'https://picsum.photos/seed/hotel-centre-bethanie-2/1200/800'),
  ('Hotel Centre Bethanie', 'photo', 'gallery', 'https://picsum.photos/seed/hotel-centre-bethanie-3/1200/800'),
  ('Hotel Centre Bethanie', 'photo', 'room', 'https://picsum.photos/seed/hotel-centre-bethanie-4/1000/700'),
  ('Hotel Ibis Huye', 'photo', 'profile', 'https://picsum.photos/seed/hotel-ibis-huye-0/800/800'),
  ('Hotel Ibis Huye', 'photo', 'landscape', 'https://picsum.photos/seed/hotel-ibis-huye-1/1200/800'),
  ('Hotel Ibis Huye', 'photo', 'gallery', 'https://picsum.photos/seed/hotel-ibis-huye-2/1200/800'),
  ('Hotel Ibis Huye', 'photo', 'gallery', 'https://picsum.photos/seed/hotel-ibis-huye-3/1200/800'),
  ('Hotel Ibis Huye', 'photo', 'room', 'https://picsum.photos/seed/hotel-ibis-huye-4/1000/700'),
  ('Hotel Faucon', 'photo', 'profile', 'https://picsum.photos/seed/hotel-faucon-0/800/800'),
  ('Hotel Faucon', 'photo', 'landscape', 'https://picsum.photos/seed/hotel-faucon-1/1200/800'),
  ('Hotel Faucon', 'photo', 'gallery', 'https://picsum.photos/seed/hotel-faucon-2/1200/800'),
  ('Hotel Faucon', 'photo', 'gallery', 'https://picsum.photos/seed/hotel-faucon-3/1200/800'),
  ('Hotel Faucon', 'photo', 'room', 'https://picsum.photos/seed/hotel-faucon-4/1000/700'),
  ('Hotel Credo', 'photo', 'profile', 'https://picsum.photos/seed/hotel-credo-0/800/800'),
  ('Hotel Credo', 'photo', 'landscape', 'https://picsum.photos/seed/hotel-credo-1/1200/800'),
  ('Hotel Credo', 'photo', 'gallery', 'https://picsum.photos/seed/hotel-credo-2/1200/800'),
  ('Hotel Credo', 'photo', 'gallery', 'https://picsum.photos/seed/hotel-credo-3/1200/800'),
  ('Hotel Credo', 'photo', 'room', 'https://picsum.photos/seed/hotel-credo-4/1000/700'),
  ('Kigali Marriott Hotel', 'photo', 'profile', 'https://picsum.photos/seed/kigali-marriott-hotel-0/800/800'),
  ('Kigali Marriott Hotel', 'photo', 'landscape', 'https://picsum.photos/seed/kigali-marriott-hotel-1/1200/800'),
  ('Kigali Marriott Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/kigali-marriott-hotel-2/1200/800'),
  ('Kigali Marriott Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/kigali-marriott-hotel-3/1200/800'),
  ('Kigali Marriott Hotel', 'photo', 'room', 'https://picsum.photos/seed/kigali-marriott-hotel-4/1000/700'),
  ('The Retreat by Heaven', 'photo', 'profile', 'https://picsum.photos/seed/the-retreat-by-heaven-0/800/800'),
  ('The Retreat by Heaven', 'photo', 'landscape', 'https://picsum.photos/seed/the-retreat-by-heaven-1/1200/800'),
  ('The Retreat by Heaven', 'photo', 'gallery', 'https://picsum.photos/seed/the-retreat-by-heaven-2/1200/800'),
  ('The Retreat by Heaven', 'photo', 'gallery', 'https://picsum.photos/seed/the-retreat-by-heaven-3/1200/800'),
  ('The Retreat by Heaven', 'photo', 'room', 'https://picsum.photos/seed/the-retreat-by-heaven-4/1000/700'),
  ('Heaven Restaurant & Boutique Hotel', 'photo', 'profile', 'https://picsum.photos/seed/heaven-restaurant-boutique-hotel-0/800/800'),
  ('Heaven Restaurant & Boutique Hotel', 'photo', 'landscape', 'https://picsum.photos/seed/heaven-restaurant-boutique-hotel-1/1200/800'),
  ('Heaven Restaurant & Boutique Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/heaven-restaurant-boutique-hotel-2/1200/800'),
  ('Heaven Restaurant & Boutique Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/heaven-restaurant-boutique-hotel-3/1200/800'),
  ('Heaven Restaurant & Boutique Hotel', 'photo', 'room', 'https://picsum.photos/seed/heaven-restaurant-boutique-hotel-4/1000/700'),
  ('Four Points by Sheraton Kigali', 'photo', 'profile', 'https://picsum.photos/seed/four-points-by-sheraton-kigali-0/800/800'),
  ('Four Points by Sheraton Kigali', 'photo', 'landscape', 'https://picsum.photos/seed/four-points-by-sheraton-kigali-1/1200/800'),
  ('Four Points by Sheraton Kigali', 'photo', 'gallery', 'https://picsum.photos/seed/four-points-by-sheraton-kigali-2/1200/800'),
  ('Four Points by Sheraton Kigali', 'photo', 'gallery', 'https://picsum.photos/seed/four-points-by-sheraton-kigali-3/1200/800'),
  ('Four Points by Sheraton Kigali', 'photo', 'room', 'https://picsum.photos/seed/four-points-by-sheraton-kigali-4/1000/700'),
  ('Park Inn by Radisson Kigali', 'photo', 'profile', 'https://picsum.photos/seed/park-inn-by-radisson-kigali-0/800/800'),
  ('Park Inn by Radisson Kigali', 'photo', 'landscape', 'https://picsum.photos/seed/park-inn-by-radisson-kigali-1/1200/800'),
  ('Park Inn by Radisson Kigali', 'photo', 'gallery', 'https://picsum.photos/seed/park-inn-by-radisson-kigali-2/1200/800'),
  ('Park Inn by Radisson Kigali', 'photo', 'gallery', 'https://picsum.photos/seed/park-inn-by-radisson-kigali-3/1200/800'),
  ('Park Inn by Radisson Kigali', 'photo', 'room', 'https://picsum.photos/seed/park-inn-by-radisson-kigali-4/1000/700'),
  ('Ubumwe Grande Hotel', 'photo', 'profile', 'https://picsum.photos/seed/ubumwe-grande-hotel-0/800/800'),
  ('Ubumwe Grande Hotel', 'photo', 'landscape', 'https://picsum.photos/seed/ubumwe-grande-hotel-1/1200/800'),
  ('Ubumwe Grande Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/ubumwe-grande-hotel-2/1200/800'),
  ('Ubumwe Grande Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/ubumwe-grande-hotel-3/1200/800'),
  ('Ubumwe Grande Hotel', 'photo', 'room', 'https://picsum.photos/seed/ubumwe-grande-hotel-4/1000/700'),
  ('M Hotel Kigali', 'photo', 'profile', 'https://picsum.photos/seed/m-hotel-kigali-0/800/800'),
  ('M Hotel Kigali', 'photo', 'landscape', 'https://picsum.photos/seed/m-hotel-kigali-1/1200/800'),
  ('M Hotel Kigali', 'photo', 'gallery', 'https://picsum.photos/seed/m-hotel-kigali-2/1200/800'),
  ('M Hotel Kigali', 'photo', 'gallery', 'https://picsum.photos/seed/m-hotel-kigali-3/1200/800'),
  ('M Hotel Kigali', 'photo', 'room', 'https://picsum.photos/seed/m-hotel-kigali-4/1000/700'),
  ('Lemigo Hotel', 'photo', 'profile', 'https://picsum.photos/seed/lemigo-hotel-0/800/800'),
  ('Lemigo Hotel', 'photo', 'landscape', 'https://picsum.photos/seed/lemigo-hotel-1/1200/800'),
  ('Lemigo Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/lemigo-hotel-2/1200/800'),
  ('Lemigo Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/lemigo-hotel-3/1200/800'),
  ('Lemigo Hotel', 'photo', 'room', 'https://picsum.photos/seed/lemigo-hotel-4/1000/700'),
  ('Mythos Hotel', 'photo', 'profile', 'https://picsum.photos/seed/mythos-hotel-0/800/800'),
  ('Mythos Hotel', 'photo', 'landscape', 'https://picsum.photos/seed/mythos-hotel-1/1200/800'),
  ('Mythos Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/mythos-hotel-2/1200/800'),
  ('Mythos Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/mythos-hotel-3/1200/800'),
  ('Mythos Hotel', 'photo', 'room', 'https://picsum.photos/seed/mythos-hotel-4/1000/700'),
  ('Grand Legacy Hotel', 'photo', 'profile', 'https://picsum.photos/seed/grand-legacy-hotel-0/800/800'),
  ('Grand Legacy Hotel', 'photo', 'landscape', 'https://picsum.photos/seed/grand-legacy-hotel-1/1200/800'),
  ('Grand Legacy Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/grand-legacy-hotel-2/1200/800'),
  ('Grand Legacy Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/grand-legacy-hotel-3/1200/800'),
  ('Grand Legacy Hotel', 'photo', 'room', 'https://picsum.photos/seed/grand-legacy-hotel-4/1000/700'),
  ('2000 Hotel Downtown', 'photo', 'profile', 'https://picsum.photos/seed/2000-hotel-downtown-0/800/800'),
  ('2000 Hotel Downtown', 'photo', 'landscape', 'https://picsum.photos/seed/2000-hotel-downtown-1/1200/800'),
  ('2000 Hotel Downtown', 'photo', 'gallery', 'https://picsum.photos/seed/2000-hotel-downtown-2/1200/800'),
  ('2000 Hotel Downtown', 'photo', 'gallery', 'https://picsum.photos/seed/2000-hotel-downtown-3/1200/800'),
  ('2000 Hotel Downtown', 'photo', 'room', 'https://picsum.photos/seed/2000-hotel-downtown-4/1000/700'),
  ('Onomo Hotel Kigali', 'photo', 'profile', 'https://picsum.photos/seed/onomo-hotel-kigali-0/800/800'),
  ('Onomo Hotel Kigali', 'photo', 'landscape', 'https://picsum.photos/seed/onomo-hotel-kigali-1/1200/800'),
  ('Onomo Hotel Kigali', 'photo', 'gallery', 'https://picsum.photos/seed/onomo-hotel-kigali-2/1200/800'),
  ('Onomo Hotel Kigali', 'photo', 'gallery', 'https://picsum.photos/seed/onomo-hotel-kigali-3/1200/800'),
  ('Onomo Hotel Kigali', 'photo', 'room', 'https://picsum.photos/seed/onomo-hotel-kigali-4/1000/700'),
  ('Sainte Famille Hotel', 'photo', 'profile', 'https://picsum.photos/seed/sainte-famille-hotel-0/800/800'),
  ('Sainte Famille Hotel', 'photo', 'landscape', 'https://picsum.photos/seed/sainte-famille-hotel-1/1200/800'),
  ('Sainte Famille Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/sainte-famille-hotel-2/1200/800'),
  ('Sainte Famille Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/sainte-famille-hotel-3/1200/800'),
  ('Sainte Famille Hotel', 'photo', 'room', 'https://picsum.photos/seed/sainte-famille-hotel-4/1000/700'),
  ('Elevate Suites Hotel', 'photo', 'profile', 'https://picsum.photos/seed/elevate-suites-hotel-0/800/800'),
  ('Elevate Suites Hotel', 'photo', 'landscape', 'https://picsum.photos/seed/elevate-suites-hotel-1/1200/800'),
  ('Elevate Suites Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/elevate-suites-hotel-2/1200/800'),
  ('Elevate Suites Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/elevate-suites-hotel-3/1200/800'),
  ('Elevate Suites Hotel', 'photo', 'room', 'https://picsum.photos/seed/elevate-suites-hotel-4/1000/700'),
  ('The Hut Restaurant and Boutique Hotel', 'photo', 'profile', 'https://picsum.photos/seed/the-hut-restaurant-and-boutique-hotel-0/800/800'),
  ('The Hut Restaurant and Boutique Hotel', 'photo', 'landscape', 'https://picsum.photos/seed/the-hut-restaurant-and-boutique-hotel-1/1200/800'),
  ('The Hut Restaurant and Boutique Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/the-hut-restaurant-and-boutique-hotel-2/1200/800'),
  ('The Hut Restaurant and Boutique Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/the-hut-restaurant-and-boutique-hotel-3/1200/800'),
  ('The Hut Restaurant and Boutique Hotel', 'photo', 'room', 'https://picsum.photos/seed/the-hut-restaurant-and-boutique-hotel-4/1000/700'),
  ('Beausejour Hotel', 'photo', 'profile', 'https://picsum.photos/seed/beausejour-hotel-0/800/800'),
  ('Beausejour Hotel', 'photo', 'landscape', 'https://picsum.photos/seed/beausejour-hotel-1/1200/800'),
  ('Beausejour Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/beausejour-hotel-2/1200/800'),
  ('Beausejour Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/beausejour-hotel-3/1200/800'),
  ('Beausejour Hotel', 'photo', 'room', 'https://picsum.photos/seed/beausejour-hotel-4/1000/700'),
  ('Grazia Apartment', 'photo', 'profile', 'https://picsum.photos/seed/grazia-apartment-0/800/800'),
  ('Grazia Apartment', 'photo', 'landscape', 'https://picsum.photos/seed/grazia-apartment-1/1200/800'),
  ('Grazia Apartment', 'photo', 'gallery', 'https://picsum.photos/seed/grazia-apartment-2/1200/800'),
  ('Grazia Apartment', 'photo', 'gallery', 'https://picsum.photos/seed/grazia-apartment-3/1200/800'),
  ('Grazia Apartment', 'photo', 'room', 'https://picsum.photos/seed/grazia-apartment-4/1000/700'),
  ('Ndaru Luxury Suites', 'photo', 'profile', 'https://picsum.photos/seed/ndaru-luxury-suites-0/800/800'),
  ('Ndaru Luxury Suites', 'photo', 'landscape', 'https://picsum.photos/seed/ndaru-luxury-suites-1/1200/800'),
  ('Ndaru Luxury Suites', 'photo', 'gallery', 'https://picsum.photos/seed/ndaru-luxury-suites-2/1200/800'),
  ('Ndaru Luxury Suites', 'photo', 'gallery', 'https://picsum.photos/seed/ndaru-luxury-suites-3/1200/800'),
  ('Ndaru Luxury Suites', 'photo', 'room', 'https://picsum.photos/seed/ndaru-luxury-suites-4/1000/700'),
  ('Home Free Hotel', 'photo', 'profile', 'https://picsum.photos/seed/home-free-hotel-0/800/800'),
  ('Home Free Hotel', 'photo', 'landscape', 'https://picsum.photos/seed/home-free-hotel-1/1200/800'),
  ('Home Free Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/home-free-hotel-2/1200/800'),
  ('Home Free Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/home-free-hotel-3/1200/800'),
  ('Home Free Hotel', 'photo', 'room', 'https://picsum.photos/seed/home-free-hotel-4/1000/700'),
  ('Centric Hotel', 'photo', 'profile', 'https://picsum.photos/seed/centric-hotel-0/800/800'),
  ('Centric Hotel', 'photo', 'landscape', 'https://picsum.photos/seed/centric-hotel-1/1200/800'),
  ('Centric Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/centric-hotel-2/1200/800'),
  ('Centric Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/centric-hotel-3/1200/800'),
  ('Centric Hotel', 'photo', 'room', 'https://picsum.photos/seed/centric-hotel-4/1000/700'),
  ('Amata n’Ubuki Hotel', 'photo', 'profile', 'https://picsum.photos/seed/amata-n-ubuki-hotel-0/800/800'),
  ('Amata n’Ubuki Hotel', 'photo', 'landscape', 'https://picsum.photos/seed/amata-n-ubuki-hotel-1/1200/800'),
  ('Amata n’Ubuki Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/amata-n-ubuki-hotel-2/1200/800'),
  ('Amata n’Ubuki Hotel', 'photo', 'gallery', 'https://picsum.photos/seed/amata-n-ubuki-hotel-3/1200/800'),
  ('Amata n’Ubuki Hotel', 'photo', 'room', 'https://picsum.photos/seed/amata-n-ubuki-hotel-4/1000/700'),
  ('Touch Africa Residence', 'photo', 'profile', 'https://picsum.photos/seed/touch-africa-residence-0/800/800'),
  ('Touch Africa Residence', 'photo', 'landscape', 'https://picsum.photos/seed/touch-africa-residence-1/1200/800'),
  ('Touch Africa Residence', 'photo', 'gallery', 'https://picsum.photos/seed/touch-africa-residence-2/1200/800'),
  ('Touch Africa Residence', 'photo', 'gallery', 'https://picsum.photos/seed/touch-africa-residence-3/1200/800'),
  ('Touch Africa Residence', 'photo', 'room', 'https://picsum.photos/seed/touch-africa-residence-4/1000/700'),
  ('The Nest Boutique', 'photo', 'profile', 'https://picsum.photos/seed/the-nest-boutique-0/800/800'),
  ('The Nest Boutique', 'photo', 'landscape', 'https://picsum.photos/seed/the-nest-boutique-1/1200/800'),
  ('The Nest Boutique', 'photo', 'gallery', 'https://picsum.photos/seed/the-nest-boutique-2/1200/800'),
  ('The Nest Boutique', 'photo', 'gallery', 'https://picsum.photos/seed/the-nest-boutique-3/1200/800'),
  ('The Nest Boutique', 'photo', 'room', 'https://picsum.photos/seed/the-nest-boutique-4/1000/700')
) AS v(hotel_name, media_type, cat, url) ON v.hotel_name = h.name
WHERE NOT EXISTS (SELECT 1 FROM hotel_media m WHERE m.hotel_id = h.id);
