import {
    StyleSheet,
    Text,
    View,
    SafeAreaView,
    ScrollView,
    TouchableOpacity
  } from "react-native";
  import React from "react";
  import { useNavigation } from "@react-navigation/native";
  import Ionicons from "@expo/vector-icons/Ionicons";
  
  const TermsConditionsScreen = () => {
    const navigation = useNavigation();
  
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => navigation.goBack()}>
            <Ionicons name="arrow-back" size={24} color="#333" />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Terms & Conditions</Text>
          <View style={{ width: 24 }} />
        </View>

        <ScrollView style={styles.scrollContainer}>
          <View style={styles.section}>
            <Text style={styles.lastUpdated}>Last Updated: July 19, 2026</Text>

            <Text style={styles.introText}>
              Please read these Terms and Conditions ("Terms") carefully before
              using the Via Travels mobile application (the "Service"). Via
              Travels is an intelligent travel planning application for tourism
              in Rwanda, developed as a capstone research project at the
              African Leadership University ("we", "us", or "our").
            </Text>

            <Text style={styles.introText}>
              Your access to and use of the Service is conditioned upon your
              acceptance of and compliance with these Terms. These Terms apply
              to all visitors, users, and others who wish to access or use the
              Service.
            </Text>

            <Text style={styles.introText}>
              By accessing or using the Service, you agree to be bound by these
              Terms. If you disagree with any part of the Terms, you do not
              have permission to access the Service.
            </Text>

            <View style={styles.termsSection}>
              <Text style={styles.termTitle}>1. Nature of the Service</Text>
              <Text style={styles.termContent}>
                1.1. Via Travels helps you plan trips to Rwanda. Based on your
                travel dates, budget, group size, and interests, the Service
                generates personalized day-by-day itineraries covering
                accommodation options, attractions, activities, transport, and
                estimated costs in Rwandan Francs (RWF) and US Dollars (USD).
              </Text>
              <Text style={styles.termContent}>
                1.2. You are responsible for maintaining the confidentiality of
                your account and password and for all activity that occurs
                under your account.
              </Text>
            </View>

            <View style={styles.termsSection}>
              <Text style={styles.termTitle}>
                2. AI-Generated Itineraries
              </Text>
              <Text style={styles.termContent}>
                2.1. Itineraries are generated by an artificial intelligence
                model grounded in a curated dataset of Rwanda tourism
                information verified against official sources, including
                Rwanda Development Board listings and confirmed local
                operators.
              </Text>
              <Text style={styles.termContent}>
                2.2. Prices, permit fees, opening hours, and availability
                reflect the most recent verification date of each entry and
                may have changed since. Always confirm current prices, permit
                requirements, and availability directly with the relevant
                provider or the Rwanda Development Board before committing to
                travel arrangements.
              </Text>
              <Text style={styles.termContent}>
                2.3. Generated itineraries are planning suggestions, not
                professional travel advice, and do not constitute an offer or
                guarantee of any service by any accommodation, activity, or
                transport provider mentioned.
              </Text>
            </View>

            <View style={styles.termsSection}>
              <Text style={styles.termTitle}>
                3. No Bookings or Payments
              </Text>
              <Text style={styles.termContent}>
                3.1. The Service is an informational planning tool. It does not
                process bookings, reservations, or payments, and does not
                check real-time availability or live pricing.
              </Text>
              <Text style={styles.termContent}>
                3.2. Any booking you make with a provider listed in an
                itinerary is a direct agreement between you and that provider.
                We are not a party to that agreement and are not responsible
                for its performance, cancellation, or refund terms.
              </Text>
            </View>

            <View style={styles.termsSection}>
              <Text style={styles.termTitle}>4. User Content</Text>
              <Text style={styles.termContent}>
                4.1. The Service allows you to save itineraries and submit
                ratings and feedback comments ("Content"). You are responsible
                for the Content you submit, including its legality and
                appropriateness.
              </Text>
              <Text style={styles.termContent}>
                4.2. By submitting Content, you grant us a non-exclusive
                license to store and use it to operate and improve the
                Service, including aggregated, anonymized analysis of
                feedback scores.
              </Text>
            </View>

            <View style={styles.termsSection}>
              <Text style={styles.termTitle}>
                5. Data Privacy
              </Text>
              <Text style={styles.termContent}>
                5.1. We collect only the information needed to operate the
                Service: your account details (name, email), your travel
                preference inputs, saved itineraries, and feedback.
              </Text>
              <Text style={styles.termContent}>
                5.2. Personal data is processed in accordance with Law No.
                058/2021 of 13/10/2021 Relating to the Protection of Personal
                Data and Privacy of the Republic of Rwanda. Your data is not
                sold or shared with third parties for marketing purposes.
              </Text>
              <Text style={styles.termContent}>
                5.3. Where the Service is used in research evaluation
                sessions, participation is governed by a separate informed
                consent process; evaluation responses are anonymized and are
                not linked to your account in any published results.
              </Text>
            </View>

            <View style={styles.termsSection}>
              <Text style={styles.termTitle}>6. Research Prototype</Text>
              <Text style={styles.termContent}>
                The Service is provided as a research prototype developed as
                part of a BSc. Software Engineering capstone project. Features,
                data coverage, and availability may change, and the Service
                may be interrupted, modified, or discontinued without notice.
              </Text>
            </View>

            <View style={styles.termsSection}>
              <Text style={styles.termTitle}>7. Intellectual Property</Text>
              <Text style={styles.termContent}>
                The Service and its original content (excluding Content
                submitted by users), features, and functionality remain our
                exclusive property. Third-party names, trademarks, and listings
                referenced in itineraries (such as hotels, parks, and
                attractions) remain the property of their respective owners and
                are used for informational purposes only.
              </Text>
            </View>

            <View style={styles.termsSection}>
              <Text style={styles.termTitle}>8. Limitation of Liability</Text>
              <Text style={styles.termContent}>
                To the maximum extent permitted by applicable law, we shall not
                be liable for any indirect, incidental, special, consequential,
                or punitive damages, or any loss of profits or data, arising
                from (i) your access to or use of, or inability to access or
                use, the Service; (ii) reliance on any itinerary, price
                estimate, or other information generated by the Service; or
                (iii) the acts or omissions of any third-party provider
                referenced in an itinerary.
              </Text>
            </View>

            <View style={styles.termsSection}>
              <Text style={styles.termTitle}>9. Governing Law</Text>
              <Text style={styles.termContent}>
                These Terms shall be governed by and construed in accordance
                with the laws of the Republic of Rwanda, without regard to its
                conflict of law provisions. Our failure to enforce any right or
                provision of these Terms will not be considered a waiver of
                those rights.
              </Text>
            </View>

            <View style={styles.termsSection}>
              <Text style={styles.termTitle}>10. Changes to Terms</Text>
              <Text style={styles.termContent}>
                We reserve the right to modify or replace these Terms at any
                time. If a revision is material, we will provide reasonable
                notice within the application before the new terms take
                effect.
              </Text>
            </View>

            <View style={styles.termsSection}>
              <Text style={styles.termTitle}>11. Contact Us</Text>
              <Text style={styles.termContent}>
                If you have any questions about these Terms, please contact us
                at support@viatravels.app.
              </Text>
            </View>
          </View>
        </ScrollView>
      </SafeAreaView>
    );
  };
  
  const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#f8f9fa",
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: 16,
      backgroundColor: "white",
      borderBottomWidth: 1,
      borderBottomColor: "#e1e4e8",
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: "#333",
    },
    scrollContainer: {
      flex: 1,
    },
    section: {
      backgroundColor: "white",
      margin: 16,
      padding: 16,
      borderRadius: 8,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    lastUpdated: {
      fontSize: 14,
      color: "#777",
      marginBottom: 16,
      fontStyle: "italic",
    },
    introText: {
      fontSize: 16,
      color: "#333",
      lineHeight: 24,
      marginBottom: 16,
    },
    termsSection: {
      marginTop: 16,
      marginBottom: 24,
    },
    termTitle: {
      fontSize: 18,
      fontWeight: "600",
      color: "#333",
      marginBottom: 8,
    },
    termContent: {
      fontSize: 16,
      color: "#333",
      lineHeight: 24,
      marginBottom: 8,
    },
  });
  
  export default TermsConditionsScreen;